Repository stolostron/cluster-proxy-addon, pull requests merged in 2024-12, with the labels that each got.

#190 Ugrade go version in dockerfiles.
  Dockerfile
  Dockerfile.rhtap
Labels: approved, dco-signoff: yes

#191 Upgrade base images and sperate build commands.
  Dockerfile
  Dockerfile.rhtap
Labels: approved, dco-signoff: yes

#192 :seedling: [main] update konflux files
  .tekton/OWNERS
  .tekton/cluster-proxy-addon-mce-28-pull-request.yaml
  .tekton/cluster-proxy-addon-mce-28-push.yaml
Labels: dco-signoff: yes

#193 No-op to rebuild for Prow update
  README.md
Labels: approved, lgtm, dco-signoff: yes

#198 :seedling: [backplane-2.5] update konflux files
  .tekton/OWNERS
  .tekton/cluster-proxy-addon-ezmt-pull-request.yaml
  .tekton/cluster-proxy-addon-ezmt-push.yaml
  .tekton/cluster-proxy-addon-mce-25-pull-request.yaml
  .tekton/cluster-proxy-addon-mce-25-push.yaml
Labels: dco-signoff: yes

#199 :seedling: [backplane-2.6] update konflux files
  .tekton/OWNERS
  .tekton/cluster-proxy-addon-mce-26-pull-request.yaml
  .tekton/cluster-proxy-addon-mce-26-push.yaml
Labels: dco-signoff: yes

#200 :seedling: [backplane-2.7] update konflux files
  .tekton/OWNERS
  .tekton/cluster-proxy-addon-mce-27-pull-request.yaml
  .tekton/cluster-proxy-addon-mce-27-push.yaml
Labels: dco-signoff: yes

#201 Remove `--cipher-suites` in the chart for test.
  chart/cluster-proxy-addon/templates/managedproxyconfiguration.yaml
Labels: approved, dco-signoff: yes
